# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  #schedule:
  #  - cron: '30 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -x
          ls $GITHUB_WORKSPACE
          curl https://cicd-test-1.s3.abci.ai/status.md > $GITHUB_WORKSPACE/content/status.md
          cat $GITHUB_WORKSPACE/content/status.md
          git config --local user.email "github-action@example.com"
          git config --local user.name "github action workflow main"
          git commit -m "auto build" $GITHUB_WORKSPACE/content/status.md
          git push origin master
        shell: bash          

      #- name: Slack Notification Test
      #  uses: rtCamp/action-slack-notify@v2
      #  env:
      #      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      #      SLACK_MESSAGE: '<!channel> ghtest'


